### ISSUE TITLE
UTF-8 encoding for all output

### ISSUE THREAD

**Issue by mkzero** [Bytespeicher/Bytebot#76]
Output using encode('ascii') should replace this with encode('utf-8'), so unicode characters are displayed properly.

**Comment by mkzero** [comment]
shorurl reports the following:

    2015-11-05 13:37:28+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
	    self.run()
	  File "/usr/lib/python2.7/threading.py", line 763, in run
	    self.__target(*self.__args, **self.__kwargs)
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 241, in inContext
	    result = inContext.theWork()
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 257, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/home/bytebot/Bytebot/plugins/shorturl.py", line 101, in onPrivmsg
	    irc.msg(channel, desc.encode('utf-8', 'replace'))
	exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 30: ordinal not in range(128)
