### ISSUE TITLE
Exception in recurrence dates

### ISSUE THREAD

**Issue by mape2k** [Bytespeicher/Bytebot#88]
plugin "dates" report the following:

    2015-11-16 15:34:51+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
	    self.run()
	  File "/usr/lib/python2.7/threading.py", line 763, in run
	    self.__target(*self.__args, **self.__kwargs)
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 241, in inContext
	    result = inContext.theWork()
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 257, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/home/bytebot/Bytebot/plugins/dates.py", line 126, in onPrivmsg
	    for e in rset.between(now, then):
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/dateutil/rrule.py", line 234, in between
	    for i in gen:
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/dateutil/rrule.py", line 1144, in _iter
	    self._genitem(rlist, gen)
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/dateutil/rrule.py", line 1082, in __init__
	    self.dt = advance_iterator(gen)
	  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/dateutil/rrule.py", line 652, in _iter
	    if until and res > until:
	exceptions.TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by suicider** [comment]
There is a (new?) timezone parameter in the recurrence-rule that is not included in `dates.py`. A possible fix is this change in line 111:

    rset.rrule(rrulestr(ical_rrule, dtstart=parse(ical_dtstart), ignoretz=1))
