### ISSUE TITLE
Connection loss with exception

### ISSUE THREAD

**Issue by mape2k** [Bytespeicher/Bytebot#90]
Bot leaves IRC Channel after the following Errors:

```
2015-11-17 18:32:21+0100 [-] Unhandled error in Deferred:
2015-11-17 18:32:21+0100 [-] Unhandled Error
Traceback (most recent call last):
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/task.py", line 213, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1148, in _sendHeartbeat
    self.sendLine('PING ' + self.hostname)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1117, in sendLine
    self._reallySendLine(line)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1113, in _reallySendLine
    return basic.LineReceiver.sendLine(self, lowQuote(line) + '\r')
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 635, in sendLine
    return self.transport.write(line + self.delimiter)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 530, in write
    self._write(bytes)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 573, in _write
    self._flushSendBIO()
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 343, in _flushSendBIO
    self.transport.write(bytes)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/_newtls.py", line 191, in write
    FileDescriptor.write(self, bytes)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/abstract.py", line 355, in write
    self.startWriting()
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/abstract.py", line 442, in startWriting
    self.reactor.addWriter(self)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 288, in addWriter
    EPOLLOUT, EPOLLIN)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 255, in _add
    self._poller.modify(fd, flags)
exceptions.IOError: [Errno 2] No such file or directory

2015-11-17 18:32:21+0100 [ByteBot (TLSMemoryBIOProtocol),client] Unhandled Error
Traceback (most recent call last):
  File "/home/bytebot/Bytebot/bytebot.py", line 196, in <module>
    reactor.run()
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1206, in mainLoop
    self.doIteration(t)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 396, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 610, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 255, in _disconnectSelectable
    selectable.connectionLost(f)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 479, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 293, in connectionLost
    protocol.connectionLost(reason)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 477, in connectionLost
    ProtocolWrapper.connectionLost(self, reason)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 125, in connectionLost
    self.wrappedProtocol.connectionLost(reason)
  File "/home/bytebot/Bytebot/bytebot.py", line 37, in connectionLost
    irc.IRCClient.connectionLost(self, reason)
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1134, in connectionLost
    self.stopHeartbeat()
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1159, in stopHeartbeat
    self._heartbeat.stop()
  File "/home/bytebot/Bytebot/env/local/lib/python2.7/site-packages/twisted/internet/task.py", line 176, in stop
    assert self.running, ("Tried to stop a LoopingCall that was "
exceptions.AssertionError: Tried to stop a LoopingCall that was not running.
```

**Comment by mkzero** [comment]
Probably not a problem after solving #111?

**Comment by mape2k** [comment]
ACK
